master:
  componentName: jenkins-master
  image: "jenkins/jenkins"
  tag: "lts"
  imagePullPolicy: "Always"
  useSecurity: true
  adminUser: admin
  adminPassword: "admin"
  resources:
    requests:
      cpu: "50m"
      memory: "256Mi"
    limits:
      cpu: "2000m"
      memory: "4096Mi"

  JCasC:
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: Welcome to Jenkins configured and managed 'as code'.

  installPlugins:
    - kubernetes:1.25.7
    - workflow-job:2.39
    - workflow-aggregator:2.6
    - credentials-binding:1.23
    - git:4.2.2
    - configuration-as-code:1.41
